= iOS Frequently Asked Questions (FAQ)
:page-aliases: ios_faq.adoc
:toc: right
:hardbreaks:
:oauth2-app-url: https://marketplace.owncloud.com/apps/oauth2
:ios-legacy-appstore-url: https://apps.apple.com/app/id543672169
:ios-app-tx-url: https://www.transifex.com/owncloud-org/owncloud/mobile-ios-app/
:ios-app-beta-url: https://owncloud.com/beta-testing/#ios
:defining-your-file-provider-url: https://developer.apple.com/documentation/fileprovider/content_and_change_tracking/defining_your_file_provider_s_content#2897861

== Introduction

Here you can find some of the most frequently asked questions about the ownCloud iOS app.

== Usage

=== Compatibility With ownCloud Server Older Than Version 10.0

Previous ownCloud iOS app with support for ownCloud Server < 10.0 is still available in {ios-legacy-appstore-url}[App Store].

=== Compatibility With iOS Versions Older Than iOS 12.0

Previous ownCloud iOS app with support for iOS < 12.0 is still available in {ios-legacy-appstore-url}[App Store].

=== Login With TOTP and Other 2FA

ownCloud server must have {oauth2-app-url}[the OAuth2 app] installed, configured, and enabled to use Two-Factor Authentication. Please contact your ownCloud administrator for more details.

== Feature Requests

=== FileProvider: Access Full Folder, Not Only Single Files

This seems like a bigger challenge for us. We track the status here:
https://github.com/owncloud/ios-app/issues/604

=== FileProvider: Support "Recent items" and "Favorites"

To support "Recent items" and "Favorites" in the iOS Files app, implementation of the {defining-your-file-provider-url}[Working Set] is needed. This is one of the next roadmap items, but there's no ETA yet.

=== Text Editing Inside the iOS App

Currently this isn't a planned feature. Focus is more to build the best integration in serious 3rd party text editing app.

Here you can find previous discussions:
https://github.com/owncloud/ios-app/issues/317

=== Missing Translations or Translation Bugs

You can help translate in your language or fix a bug.

We use Transifex for translations. Please {ios-app-tx-url}[register here] for an account and join the global community.

=== Testing New Features

Use {ios-app-beta-url}[this link] to join the beta program on iOS.
